const PREFIX = 'TOOLBAR_'

export const CLICK_BUTTON      = PREFIX + 'CLICK_BUTTON'
export const MOUSE_DOWN_BUTTON = PREFIX + 'MOUSE_DOWN_BUTTON'
export const MOUSE_UP_BUTTON   = PREFIX + 'MOUSE_UP_BUTTON'
export const MOUSE_MOVE_BUTTON = PREFIX + 'MOUSE_MOVE_BUTTON'