const PREFIX = 'TOOLBAR_'

export const CLICK_BUTTON      = PREFIX + 'CLICK_BUTTON'
export const DRAG_START_BUTTON = PREFIX + 'DRAG_START_BUTTON'
export const DRAG_END_BUTTON   = PREFIX + 'DRAG_END_BUTTON'
export const SWITCH_BUTTON     = PREFIX + 'SWITCH_BUTTON'